pipeline {
agent any

stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Test') {
        steps {
            dir('cicd-demo') {
                sh 'npm install'
                sh 'npm test'
            }
        }
    }

    stage('Docker Build') {
        steps {
            dir('cicd-demo') {
                sh 'docker build -t cicd-demo:v1 .'
            }
        }
    }

    stage('Deploy') {
        steps {
            dir('cicd-demo') {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}

}