pipeline {
agent any

stages {

    stage('Environment Check') {
        steps {
            sh '''
                echo "PATH=$PATH"
                which sh
                which docker
                which kubectl
            '''
        }
    }

    stage('Docker Build') {
        steps {
            dir('cicd-demo') {
                sh 'docker build -t cicd-demo:v1 .'
            }
        }
    }

    stage('Deploy') {
        steps {
            dir('cicd-demo') {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}

}